name: reviewdog
on: [pull_request]
jobs:
  vimlint:
    name: runner / vimlint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: vimlint-github-pr-check
        uses: tsuyoshicho/action-vimlint@master
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-check
      - name: vimlint-github-check
        uses: tsuyoshicho/action-vimlint@master
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-check
      - name: vimlint-pr-review
        uses: tsuyoshicho/action-vimlint@master
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-review
